### ISSUE TITLE
HELP! is not dropping multiplied items and generates error in console

### ISSUE THREAD

**Issue by TiagoBrazil** [Nathat23/StackMob-3#256] opened 2019-07-15 17:17 UTC
**Describe the bug**
Is'nt dropping multiplied items and generates error in console (XP too)
http://prntscr.com/ofdm6v

Console error: http://prntscr.com/ofdmmz

V1.14

**To Reproduce**

**Expected behavior**

**Screenshots/Videos**

**Bukkit/Spigot AND StackMob version:**
Self explanatory.

**Additional context**

**Comment by Nathat23** [comment] 2019-07-17 19:27
Duplicate of  #243

**Closed by Nathat23** 2019-07-17 19:27 UTC
