### ISSUE TITLE
Could not pass event EntityDeathEvent to StackMob v4.0.0

### ISSUE THREAD

**Issue by naisencu** [Nathat23/StackMob-3#243] opened 2019-06-14 10:34 UTC
Stacked mobs behaving as single mob.
For example , when killing 7x skeletons, it drops a loot of single skeleton and it vanishes. It is supposed to drop the loot of single skeleton and turn into 6x skeleton but somehow the other 6x skeleton vanishes.
Spigot 1.14 Stackmobs v4.0.0
Video is linked below :
https://drive.google.com/open?id=1TKUPel43SHKFY7La5ISqnU9BDL4w8mln
https://drive.google.com/open?id=17hUctxuLwscerRZEODd0malCBvhLmGLt

**Comment by Nathat23** [comment] 2019-06-22 08:11
Can you provide the error?

**Comment by ArtelGG** [comment] 2019-07-01 04:03
I've been getting an error like this lately too.
```
30.06 22:59:41 [Server] ERROR Could not pass event EntityDeathEvent to StackMob v4.0.2
30.06 22:59:41 [Server] INFO java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [<parameter minecraft:position>, <parameter minecraft:killer_entity>, <parameter minecraft:this_entity>, <parameter minecraft:damage_source>]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.LootTableInfo$Builder.build(SourceFile:184) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftLootTable.convertContext(CraftLootTable.java:93) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftLootTable.populateLoot(CraftLootTable.java:43) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at uk.antiperson.stackmob.entity.multiplication.DropTools.generateLoot(DropTools.java:91) ~[?:?]
30.06 22:59:41 [Server] INFO at uk.antiperson.stackmob.entity.multiplication.DropTools.calculateDrops(DropTools.java:49) ~[?:?]
30.06 22:59:41 [Server] INFO at uk.antiperson.stackmob.entity.multiplication.DropTools.doDrops(DropTools.java:36) ~[?:?]
30.06 22:59:41 [Server] INFO at uk.antiperson.stackmob.listeners.entity.DeathEvent.multiplication(DeathEvent.java:57) ~[?:?]
30.06 22:59:41 [Server] INFO at uk.antiperson.stackmob.listeners.entity.DeathEvent.onDeath(DeathEvent.java:45) ~[?:?]
30.06 22:59:41 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
30.06 22:59:41 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:741) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1416) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1354) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1198) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.EntityHuman.attack(EntityHuman.java:1031) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.EntityPlayer.attack(EntityPlayer.java:1676) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2062) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:979) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-111]
30.06 22:59:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by Nathat23** [comment] 2019-07-17 19:32
Do any of you know what causes this?

**Comment by ArtelGG** [comment] 2019-07-18 01:33
Nope. I had to stop using StackMob because of how much lag it was creating. I have never seen an error like that on older versions so I'm assuming it's something new from 1.13/1.14.

**Comment by Nathat23** [comment] 2019-08-09 10:22
duplicate of #234

**Closed by Nathat23** 2019-08-09 10:22 UTC
Labels: bug, waiting for reply
