### ISSUE TITLE
1.14.2 -  Error occurred while enabling StackMob v4.0.0 (Is it up to date?)

### ISSUE THREAD

**Issue by comonier** [Nathat23/StackMob-3#247] opened 2019-06-20 07:32 UTC
[03:30:20] [Server thread/INFO]: [StackMob] Enabling StackMob v4.0.0
[03:30:20] [Server thread/INFO]: [StackMob] StackMob v4.0.0 created by antiPerson (pas_francais)
[03:30:20] [Server thread/INFO]: [StackMob] Documentation can be found at https://www.spigotmc.org/resources/stackmob.29999/
[03:30:20] [Server thread/INFO]: [StackMob] GitHub repository can be found at https://www.github.com/Nathat23/StackMob-2
[03:30:20] [Server thread/INFO]: [StackMob] Detected server version: V1_14
[03:30:20] [Server thread/ERROR]: Error occurred while enabling StackMob v4.0.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at uk.antiperson.stackmob.config.ConfigLoader.copyDefault(ConfigLoader.java:83) ~[?:?]
	at uk.antiperson.stackmob.config.ConfigLoader.reloadCustomConfig(ConfigLoader.java:47) ~[?:?]
	at uk.antiperson.stackmob.config.ConfigLoader.getCustomConfig(ConfigLoader.java:58) ~[?:?]
	at uk.antiperson.stackmob.StackMob.getGeneralConfig(StackMob.java:277) ~[?:?]
	at uk.antiperson.stackmob.stick.StickTools.<init>(StickTools.java:32) ~[?:?]
	at uk.antiperson.stackmob.StackMob.initVariables(StackMob.java:141) ~[?:?]
	at uk.antiperson.stackmob.StackMob.onEnable(StackMob.java:88) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.2.jar:git-Spigot-df0eb25-8003ced]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by Nathat23** [comment] 2019-06-22 08:14
duplicate of #236

**Closed by Nathat23** 2019-06-22 08:14 UTC
