### ISSUE TITLE
I m not sure is this a bug or....

### ISSUE THREAD

**Issue by iamtooboring1234** [Nathat23/StackMob-3#260] opened 2019-07-19 13:45 UTC
[21:36:15] [Server thread/ERROR]: Could not pass event EntityDeathEvent to StackMob v4.0.2
--
830 | org.bukkit.event.EventException: null
831 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
832 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
833 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
834 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
835 | at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:708) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
836 | at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1365) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
837 | at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1322) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
838 | at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1169) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
839 | at net.minecraft.server.v1_14_R1.EntityLiving.af(EntityLiving.java:1756) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
840 | at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:400) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
841 | at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
842 | at net.minecraft.server.v1_14_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:210) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
843 | at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:346) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
844 | at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2217) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
845 | at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
846 | at net.minecraft.server.v1_14_R1.EntitySlime.tick(EntitySlime.java:98) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
847 | at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
848 | at net.minecraft.server.v1_14_R1.World.a(World.java:745) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
849 | at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
850 | at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
851 | at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
852 | at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
853 | at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
854 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
855 | Caused by: java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [&lt;parameter minecraft:position&gt;, &lt;parameter minecraft:this_entity&gt;, &lt;parameter minecraft:damage_source&gt;]
856 | at net.minecraft.server.v1_14_R1.LootTableInfo$Builder.build(SourceFile:184) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
857 | at org.bukkit.craftbukkit.v1_14_R1.CraftLootTable.convertContext(CraftLootTable.java:93) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
858 | at org.bukkit.craftbukkit.v1_14_R1.CraftLootTable.populateLoot(CraftLootTable.java:43) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
859 | at uk.antiperson.stackmob.entity.multiplication.DropTools.generateLoot(DropTools.java:91) ~[?:?]
860 | at uk.antiperson.stackmob.entity.multiplication.DropTools.calculateDrops(DropTools.java:49) ~[?:?]
861 | at uk.antiperson.stackmob.entity.multiplication.DropTools.doDrops(DropTools.java:36) ~[?:?]
862 | at uk.antiperson.stackmob.listeners.entity.DeathEvent.multiplication(DeathEvent.java:57) ~[?:?]
863 | at uk.antiperson.stackmob.listeners.entity.DeathEvent.onDeath(DeathEvent.java:45) ~[?:?]
864 | at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[?:?]
865 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
866 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
867 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
868 | ... 23 more
869 | [21:36:16] [Server thread/ERROR]: Could not pass event EntityDeathEvent to StackMob v4.0.2
870 | org.bukkit.event.EventException: null
871 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
872 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
873 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
874 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
875 | at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:708) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
876 | at net.minecraft.server.v1_14_R1.EntityLiving.d(EntityLiving.java:1365) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
877 | at net.minecraft.server.v1_14_R1.EntityLiving.die(EntityLiving.java:1322) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
878 | at net.minecraft.server.v1_14_R1.EntityLiving.damageEntity(EntityLiving.java:1169) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
879 | at net.minecraft.server.v1_14_R1.EntityLiving.af(EntityLiving.java:1756) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
880 | at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:400) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
881 | at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:236) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
882 | at net.minecraft.server.v1_14_R1.EntityInsentient.entityBaseTick(EntityInsentient.java:210) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
883 | at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:346) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
884 | at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2217) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
885 | at net.minecraft.server.v1_14_R1.EntityInsentient.tick(EntityInsentient.java:273) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
886 | at net.minecraft.server.v1_14_R1.EntitySlime.tick(EntitySlime.java:98) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
887 | at net.minecraft.server.v1_14_R1.WorldServer.entityJoinedWorld(WorldServer.java:570) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
888 | at net.minecraft.server.v1_14_R1.World.a(World.java:745) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
889 | at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:346) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
890 | at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1057) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
891 | at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
892 | at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
893 | at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
894 | at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
895 | Caused by: java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [&lt;parameter minecraft:position&gt;, &lt;parameter minecraft:this_entity&gt;, &lt;parameter minecraft:damage_source&gt;]
896 | at net.minecraft.server.v1_14_R1.LootTableInfo$Builder.build(SourceFile:184) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
897 | at org.bukkit.craftbukkit.v1_14_R1.CraftLootTable.convertContext(CraftLootTable.java:93) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
898 | at org.bukkit.craftbukkit.v1_14_R1.CraftLootTable.populateLoot(CraftLootTable.java:43) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
899 | at uk.antiperson.stackmob.entity.multiplication.DropTools.generateLoot(DropTools.java:91) ~[?:?]
900 | at uk.antiperson.stackmob.entity.multiplication.DropTools.calculateDrops(DropTools.java:49) ~[?:?]
901 | at uk.antiperson.stackmob.entity.multiplication.DropTools.doDrops(DropTools.java:36) ~[?:?]
902 | at uk.antiperson.stackmob.listeners.entity.DeathEvent.multiplication(DeathEvent.java:57) ~[?:?]
903 | at uk.antiperson.stackmob.listeners.entity.DeathEvent.onDeath(DeathEvent.java:45) ~[?:?]
904 | at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source) ~[?:?]
905 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
906 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
907 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[minecraft_server.jar:git-Spigot-9a643a6-eb2e657]
908 | ... 23 more

**Comment by Nathat23** [comment] 2019-08-06 09:35
Duplicate of #243 
If you know what causes this please say, since I have trouble replicating it.

**Closed by Nathat23** 2019-08-06 09:35 UTC
